### ISSUE TITLE
EPIC: Initial Django Setup

### ISSUE THREAD

**Issue by Julia-cloudname** [Julia-cloudname/marisol-furniture#1]
As a **developer**, I can **setup Django and deploy the site**, so that **I can develop the site**

**Tasks:**

- [x] Install Django and supporting libraries
- [x] Create a new blank Django project and App
- [x] Set project to use Cloudinary and PostgreSQL
- [x] Deploy empty site to Heroku 

[Guide link ](https://docs.google.com/document/d/113P2BPOkrG6rMxsrm8GCbO6CVG2b1R9htD4tRdkSltQ/edit)

**Comment by Julia-cloudname** [comment]
Completed
