### ISSUE TITLE
USER STORY: Create posts

### ISSUE THREAD

**Issue by Julia-cloudname** [Julia-cloudname/marisol-furniture#12]
EPIC: #4 

As an **admin** I can **create blog posts**, so I can **manage content**

**Acceptance Criteria**
- Admin can add new blog posts from the admin panel 
- Post form has a title, slug, author, content field with editor panel, image, status and save button
- Admin can see properties of a post (status, slug, title, created date)
- Admin can filter posts and use search-panel

**Tasks**

- [ ] Import Post model
- [ ] Install Django summernote
- [ ] Add summernote app to requitements.txt
